//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopPickbazar
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ProductName { get; set; }
        public string FeaturedImage { get; set; }
        public string Images { get; set; }
        public double Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public int Quantity { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
